/*
 * Copyright(c) The Maintainers of Nanvix.
 * Licensed under the MIT License.
 */

#ifndef _SYSLOG_H
#define _SYSLOG_H

#include <sys/cdefs.h>

/* Used in logopt for openlog() */
#define LOG_PID 0x01    /* Log the process ID with each message.  */
#define LOG_CONS 0x02   /*  Log to the system console on error. */
#define LOG_ODELAY 0x04 /* Connect to syslog daemon immediately. */
#define LOG_NDELAY 0x08 /* Delay open until syslog() is called. */
#define LOG_NOWAIT 0x10 /* Do not wait for child processes.*/

/* Used as the facility argument to openlog() */
#define LOG_KERN (0 << 3)    /* Reserved for message generated by the system. */
#define LOG_USER (1 << 3)    /* Message generated by a process. */
#define LOG_MAIL (2 << 3)    /* Reserved for message generated by mail system. */
#define LOG_DAEMON (3 << 3)  /* Reserved for message generated by system daemon. */
#define LOG_AUTH (4 << 3)    /* Reserved for message generated by authorization daemon. */
#define LOG_LPR (6 << 3)     /* Reserved for message generated by printer system. */
#define LOG_NEWS (7 << 3)    /* Reserved for message generated by news system. */
#define LOG_UUCP (8 << 3)    /* Reserved for message generated by UUCP system. */
#define LOG_CRON (9 << 3)    /* Reserved for message generated by clock daemon. */
#define LOG_LOCAL0 (16 << 3) /* Reserved for local use. */
#define LOG_LOCAL1 (17 << 3) /* Reserved for local use. */
#define LOG_LOCAL2 (18 << 3) /* Reserved for local use. */
#define LOG_LOCAL3 (19 << 3) /* Reserved for local use. */
#define LOG_LOCAL4 (20 << 3) /* Reserved for local use. */
#define LOG_LOCAL5 (21 << 3) /* Reserved for local use. */
#define LOG_LOCAL6 (22 << 3) /* Reserved for local use. */
#define LOG_LOCAL7 (23 << 3) /* Reserved for local use. */

/* A mask for priority pri. */
#define LOG_MASK(pri) (1 << (pri))

/* A mask for all priorities from LOG_EMERG through pri inclusive in the order listed in the list of priority symbolic
 * constants below. Any additional implementation-defined priorities not included in the list below shall not be
 * included in the mask. */
#define LOG_UPTO(pri) ((1 << ((pri) + 1)) - 1)

/* Used as pri argument of the LOG_MASK and LOG_UPTO macros. */
#define LOG_EMERG 0   /* A panic condition was reported to all processes. */
#define LOG_ALERT 1   /* A condition that should be corrected immediately. */
#define LOG_CRIT 2    /* A critical condition. */
#define LOG_ERR 3     /* An error message. */
#define LOG_WARNING 4 /* A warning message. */
#define LOG_NOTICE 5  /* A condition requiring special handling. */
#define LOG_INFO 6    /* A general information message. */
#define LOG_DEBUG 7   /* A message useful for debugging programs. */

__BEGIN_DECLS
extern void closelog(void);
extern void openlog(const char *, int, int);
extern int setlogmask(int);
extern void syslog(int, const char *, ...);
__END_DECLS

#endif /* _SYSLOG_H */
